insert into breed (id, name, type_id) values (1, 'Breed', 2);
insert into breed (id, name, type_id) values (2, 'Abyssinian', 2);
insert into breed (id, name, type_id) values (3, 'American Curl', 2);
insert into breed (id, name, type_id) values (4, 'American Shorthair', 2);
insert into breed (id, name, type_id) values (5, 'American Wirehair', 2);
insert into breed (id, name, type_id) values (6, 'Applehead Siamese', 2);
insert into breed (id, name, type_id) values (7, 'Balinese', 2);
insert into breed (id, name, type_id) values (8, 'Bengal', 2);
insert into breed (id, name, type_id) values (9, 'Birman', 2);
insert into breed (id, name, type_id) values (10, 'Bobtail', 2);
insert into breed (id, name, type_id) values (11, 'Bombay', 2);
insert into breed (id, name, type_id) values (12, 'British Shorthair', 2);
insert into breed (id, name, type_id) values (13, 'Burmese', 2);
insert into breed (id, name, type_id) values (14, 'Burmilla', 2);
insert into breed (id, name, type_id) values (15, 'Calico', 2);
insert into breed (id, name, type_id) values (16, 'Canadian Hairless', 2);
insert into breed (id, name, type_id) values (17, 'Chartreux', 2);
insert into breed (id, name, type_id) values (18, 'Chausie', 2);
insert into breed (id, name, type_id) values (19, 'Chinchilla', 2);
insert into breed (id, name, type_id) values (20, 'Cornish Rex', 2);
insert into breed (id, name, type_id) values (21, 'Cymric', 2);
insert into breed (id, name, type_id) values (22, 'Devon Rex', 2);
insert into breed (id, name, type_id) values (23, 'Dilute Calico', 2);
insert into breed (id, name, type_id) values (24, 'Dilute Tortoiseshell', 2);
insert into breed (id, name, type_id) values (25, 'Domestic Long Hair', 2);
insert into breed (id, name, type_id) values (26, 'Domestic Long Hair - Brown', 2);
insert into breed (id, name, type_id) values (27, 'Domestic Long Hair - Buff', 2);
insert into breed (id, name, type_id) values (28, 'Domestic Long Hair - Buff And White', 2);
insert into breed (id, name, type_id) values (29, 'Domestic Long Hair - Gray And White', 2);
insert into breed (id, name, type_id) values (30, 'Domestic Long Hair - Orange', 2);
insert into breed (id, name, type_id) values (31, 'Domestic Long Hair - Orange And White', 2);
insert into breed (id, name, type_id) values (32, 'Domestic Long Hair-Black', 2);
insert into breed (id, name, type_id) values (33, 'Domestic Long Hair-Black And White', 2);
insert into breed (id, name, type_id) values (34, 'Domestic Long Hair-Gray', 2);
insert into breed (id, name, type_id) values (35, 'Domestic Long Hair-White', 2);
insert into breed (id, name, type_id) values (36, 'Domestic Medium Hair', 2);
insert into breed (id, name, type_id) values (37, 'Domestic Medium Hair - Brown', 2);
insert into breed (id, name, type_id) values (38, 'Domestic Medium Hair - Buff', 2);
insert into breed (id, name, type_id) values (39, 'Domestic Medium Hair - Buff And White', 2);
insert into breed (id, name, type_id) values (40, 'Domestic Medium Hair - Gray And White', 2);
insert into breed (id, name, type_id) values (41, 'Domestic Medium Hair - Orange And White', 2);
insert into breed (id, name, type_id) values (42, 'Domestic Medium Hair-Black', 2);
insert into breed (id, name, type_id) values (43, 'Domestic Medium Hair-Black And White', 2);
insert into breed (id, name, type_id) values (44, 'Domestic Medium Hair-Gray', 2);
insert into breed (id, name, type_id) values (45, 'Domestic Medium Hair-Orange', 2);
insert into breed (id, name, type_id) values (46, 'Domestic Medium Hair-White', 2);
insert into breed (id, name, type_id) values (47, 'Domestic Short Hair', 2);
insert into breed (id, name, type_id) values (48, 'Domestic Short Hair - Brown', 2);
insert into breed (id, name, type_id) values (49, 'Domestic Short Hair - Buff', 2);
insert into breed (id, name, type_id) values (50, 'Domestic Short Hair - Buff And White', 2);
insert into breed (id, name, type_id) values (51, 'Domestic Short Hair - Gray And White', 2);
insert into breed (id, name, type_id) values (52, 'Domestic Short Hair - Orange And White', 2);
insert into breed (id, name, type_id) values (53, 'Domestic Short Hair-Black', 2);
insert into breed (id, name, type_id) values (54, 'Domestic Short Hair-Black And White', 2);
insert into breed (id, name, type_id) values (55, 'Domestic Short Hair-Gray', 2);
insert into breed (id, name, type_id) values (56, 'Domestic Short Hair-Mitted', 2);
insert into breed (id, name, type_id) values (57, 'Domestic Short Hair-Orange', 2);
insert into breed (id, name, type_id) values (58, 'Domestic Short Hair-White', 2);
insert into breed (id, name, type_id) values (59, 'Egyptian Mau', 2);
insert into breed (id, name, type_id) values (60, 'Exotic Shorthair', 2);
insert into breed (id, name, type_id) values (61, 'Extra-Toes Cat (Hemingway Polydactyl)', 2);
insert into breed (id, name, type_id) values (62, 'Havana', 2);
insert into breed (id, name, type_id) values (63, 'Himalayan', 2);
insert into breed (id, name, type_id) values (64, 'Japanese Bobtail', 2);
insert into breed (id, name, type_id) values (65, 'Javanese', 2);
insert into breed (id, name, type_id) values (66, 'Korat', 2);
insert into breed (id, name, type_id) values (67, 'LaPerm', 2);
insert into breed (id, name, type_id) values (68, 'Maine Coon', 2);
insert into breed (id, name, type_id) values (69, 'Manx', 2);
insert into breed (id, name, type_id) values (70, 'Munchkin', 2);
insert into breed (id, name, type_id) values (71, 'Nebelung', 2);
insert into breed (id, name, type_id) values (72, 'Norwegian Forest Cat', 2);
insert into breed (id, name, type_id) values (73, 'Ocicat', 2);
insert into breed (id, name, type_id) values (74, 'Oriental Long Hair', 2);
insert into breed (id, name, type_id) values (75, 'Oriental Short Hair', 2);
insert into breed (id, name, type_id) values (76, 'Oriental Tabby', 2);
insert into breed (id, name, type_id) values (77, 'Persian', 2);
insert into breed (id, name, type_id) values (78, 'Pixie-Bob', 2);
insert into breed (id, name, type_id) values (79, 'Ragamuffin', 2);
insert into breed (id, name, type_id) values (80, 'Ragdoll', 2);
insert into breed (id, name, type_id) values (81, 'Russian Blue', 2);
insert into breed (id, name, type_id) values (82, 'Scottish Fold', 2);
insert into breed (id, name, type_id) values (83, 'Selkirk Rex', 2);
insert into breed (id, name, type_id) values (84, 'Siamese', 2);
insert into breed (id, name, type_id) values (85, 'Siberian', 2);
insert into breed (id, name, type_id) values (86, 'Silver', 2);
insert into breed (id, name, type_id) values (87, 'Singapura', 2);
insert into breed (id, name, type_id) values (88, 'Snowshoe', 2);
insert into breed (id, name, type_id) values (89, 'Somali', 2);
insert into breed (id, name, type_id) values (90, 'Sphynx (Hairless Cat)', 2);
insert into breed (id, name, type_id) values (91, 'Tabby', 2);
insert into breed (id, name, type_id) values (92, 'Tabby - Brown', 2);
insert into breed (id, name, type_id) values (93, 'Tabby - Grey', 2);
insert into breed (id, name, type_id) values (94, 'Tabby - Orange', 2);
insert into breed (id, name, type_id) values (95, 'Tabby - Black', 2);
insert into breed (id, name, type_id) values (96, 'Tabby - Buff', 2);
insert into breed (id, name, type_id) values (97, 'Tabby - White', 2);
insert into breed (id, name, type_id) values (98, 'Tiger', 2);
insert into breed (id, name, type_id) values (99, 'Tonkinese', 2);
insert into breed (id, name, type_id) values (100, 'Torbie', 2);
insert into breed (id, name, type_id) values (101, 'Tortoiseshell', 2);
insert into breed (id, name, type_id) values (102, 'Turkish Angora', 2);
insert into breed (id, name, type_id) values (103, 'Turkish Van', 2);
insert into breed (id, name, type_id) values (104, 'Tuxedo', 2);