CREATE TABLE IF NOT EXISTS fosterstory.breed (
	id int NOT NULL,
	name varchar not NULL,
	type_id varchar NULL
);

insert into breed (id, name, type_id) values (105, 'Affenpinscher', 1);
insert into breed (id, name, type_id) values (106, 'Afghan Hound', 1);
insert into breed (id, name, type_id) values (107, 'Airedale Terrier', 1);
insert into breed (id, name, type_id) values (108, 'Akbash', 1);
insert into breed (id, name, type_id) values (109, 'Akita', 1);
insert into breed (id, name, type_id) values (110, 'Alaskan Malamute', 1);
insert into breed (id, name, type_id) values (111, 'American Bulldog', 1);
insert into breed (id, name, type_id) values (112, 'American Eskimo Dog', 1);
insert into breed (id, name, type_id) values (113, 'American Hairless Terrier', 1);
insert into breed (id, name, type_id) values (114, 'American Staffordshire Terrier', 1);
insert into breed (id, name, type_id) values (115, 'American Water Spaniel', 1);
insert into breed (id, name, type_id) values (116, 'Anatolian Shepherd', 1);
insert into breed (id, name, type_id) values (117, 'Appenzell Mountain Dog', 1);
insert into breed (id, name, type_id) values (118, 'Australian Cattle Dog (Blue Heeler)', 1);
insert into breed (id, name, type_id) values (119, 'Australian Kelpie', 1);
insert into breed (id, name, type_id) values (120, 'Australian Shepherd', 1);
insert into breed (id, name, type_id) values (121, 'Australian Terrier', 1);
insert into breed (id, name, type_id) values (122, 'Basenji', 1);
insert into breed (id, name, type_id) values (123, 'Basset Hound', 1);
insert into breed (id, name, type_id) values (124, 'Beagle', 1);
insert into breed (id, name, type_id) values (125, 'Bearded Collie', 1);
insert into breed (id, name, type_id) values (126, 'Beauceron', 1);
insert into breed (id, name, type_id) values (127, 'Bedlington Terrier', 1);
insert into breed (id, name, type_id) values (128, 'Belgian Shepherd Dog Sheepdog', 1);
insert into breed (id, name, type_id) values (129, 'Belgian Shepherd Laekenois', 1);
insert into breed (id, name, type_id) values (130, 'Belgian Shepherd Malinois', 1);
insert into breed (id, name, type_id) values (131, 'Belgian Shepherd Tervuren', 1);
insert into breed (id, name, type_id) values (132, 'Bernese Mountain Dog', 1);
insert into breed (id, name, type_id) values (133, 'Bichon Frise', 1);
insert into breed (id, name, type_id) values (134, 'Black Labrador Retriever', 1);
insert into breed (id, name, type_id) values (135, 'Black Mouth Cur', 1);
insert into breed (id, name, type_id) values (136, 'Black Russian Terrier', 1);
insert into breed (id, name, type_id) values (137, 'Black And Tan Coonhound', 1);
insert into breed (id, name, type_id) values (138, 'Bloodhound', 1);
insert into breed (id, name, type_id) values (139, 'Blue Lacy', 1);
insert into breed (id, name, type_id) values (140, 'Bluetick Coonhound', 1);
insert into breed (id, name, type_id) values (141, 'Boerboel', 1);
insert into breed (id, name, type_id) values (142, 'Bolognese', 1);
insert into breed (id, name, type_id) values (143, 'Border Collie', 1);
insert into breed (id, name, type_id) values (144, 'Border Terrier', 1);
insert into breed (id, name, type_id) values (145, 'Borzoi', 1);
insert into breed (id, name, type_id) values (146, 'Boston Terrier', 1);
insert into breed (id, name, type_id) values (147, 'Bouvier Des Flanders', 1);
insert into breed (id, name, type_id) values (148, 'Boxer', 1);
insert into breed (id, name, type_id) values (149, 'Boykin Spaniel', 1);
insert into breed (id, name, type_id) values (150, 'Briard', 1);
insert into breed (id, name, type_id) values (151, 'Brittany Spaniel', 1);
insert into breed (id, name, type_id) values (152, 'Brussels Griffon', 1);
insert into breed (id, name, type_id) values (153, 'Bull Terrier', 1);
insert into breed (id, name, type_id) values (154, 'Bullmastiff', 1);
insert into breed (id, name, type_id) values (155, 'Cairn Terrier', 1);
insert into breed (id, name, type_id) values (156, 'Canaan Dog', 1);
insert into breed (id, name, type_id) values (157, 'Cane Corso Mastiff', 1);
insert into breed (id, name, type_id) values (158, 'Carolina Dog', 1);
insert into breed (id, name, type_id) values (159, 'Catahoula Leopard Dog', 1);
insert into breed (id, name, type_id) values (160, 'Cattle Dog', 1);
insert into breed (id, name, type_id) values (161, 'Caucasian Sheepdog (Caucasian Ovtcharka)', 1);
insert into breed (id, name, type_id) values (162, 'Cavalier King Charles Spaniel', 1);
insert into breed (id, name, type_id) values (163, 'Chesapeake Bay Retriever', 1);
insert into breed (id, name, type_id) values (164, 'Chihuahua', 1);
insert into breed (id, name, type_id) values (165, 'Chinese Crested Dog', 1);
insert into breed (id, name, type_id) values (166, 'Chinese Foo Dog', 1);
insert into breed (id, name, type_id) values (167, 'Chinook', 1);
insert into breed (id, name, type_id) values (168, 'Chocolate Labrador Retriever', 1);
insert into breed (id, name, type_id) values (169, 'Chow Chow', 1);
insert into breed (id, name, type_id) values (170, 'Cirneco Dell''Etna', 1);
insert into breed (id, name, type_id) values (171, 'Clumber Spaniel', 1);
insert into breed (id, name, type_id) values (172, 'Cockapoo', 1);
insert into breed (id, name, type_id) values (173, 'Cocker Spaniel', 1);
insert into breed (id, name, type_id) values (174, 'Collie', 1);
insert into breed (id, name, type_id) values (175, 'Coonhound', 1);
insert into breed (id, name, type_id) values (176, 'Corgi', 1);
insert into breed (id, name, type_id) values (177, 'Coton De Tulear', 1);
insert into breed (id, name, type_id) values (178, 'Curly-Coated Retriever', 1);
insert into breed (id, name, type_id) values (179, 'Dachshund', 1);
insert into breed (id, name, type_id) values (180, 'Dalmatian', 1);
insert into breed (id, name, type_id) values (181, 'Dandi Dinmont Terrier', 1);
insert into breed (id, name, type_id) values (182, 'Doberman Pinscher', 1);
insert into breed (id, name, type_id) values (183, 'Dogo Argentino', 1);
insert into breed (id, name, type_id) values (184, 'Dogue De Bordeaux', 1);
insert into breed (id, name, type_id) values (185, 'Dutch Shepherd', 1);
insert into breed (id, name, type_id) values (186, 'English Bulldog', 1);
insert into breed (id, name, type_id) values (187, 'English Cocker Spaniel', 1);
insert into breed (id, name, type_id) values (188, 'English Coonhound', 1);
insert into breed (id, name, type_id) values (189, 'English Pointer', 1);
insert into breed (id, name, type_id) values (190, 'English Setter', 1);
insert into breed (id, name, type_id) values (191, 'English Shepherd', 1);
insert into breed (id, name, type_id) values (192, 'English Springer Spaniel', 1);
insert into breed (id, name, type_id) values (193, 'English Toy Spaniel', 1);
insert into breed (id, name, type_id) values (194, 'Entlebucher', 1);
insert into breed (id, name, type_id) values (195, 'Eskimo Dog', 1);
insert into breed (id, name, type_id) values (196, 'Feist', 1);
insert into breed (id, name, type_id) values (197, 'Field Spaniel', 1);
insert into breed (id, name, type_id) values (198, 'Fila Brasileiro', 1);
insert into breed (id, name, type_id) values (199, 'Finnish Lapphund', 1);
insert into breed (id, name, type_id) values (200, 'Finnish Spitz', 1);
insert into breed (id, name, type_id) values (201, 'Flat-Coated Retriever', 1);
insert into breed (id, name, type_id) values (202, 'Fox Terrier', 1);
insert into breed (id, name, type_id) values (203, 'Foxhound', 1);
insert into breed (id, name, type_id) values (204, 'French Bulldog', 1);
insert into breed (id, name, type_id) values (205, 'Galgo Spanish Greyhound', 1);
insert into breed (id, name, type_id) values (206, 'German Pinscher', 1);
insert into breed (id, name, type_id) values (207, 'German Shepherd Dog', 1);
insert into breed (id, name, type_id) values (208, 'German Shorthaired Pointer', 1);
insert into breed (id, name, type_id) values (209, 'German Spitz', 1);
insert into breed (id, name, type_id) values (210, 'German Wirehaired Pointer', 1);
insert into breed (id, name, type_id) values (211, 'Giant Schnauzer', 1);
insert into breed (id, name, type_id) values (212, 'Glen Of Imaal Terrier', 1);
insert into breed (id, name, type_id) values (213, 'Golden Retriever', 1);
insert into breed (id, name, type_id) values (214, 'Gordon Setter', 1);
insert into breed (id, name, type_id) values (215, 'Great Dane', 1);
insert into breed (id, name, type_id) values (216, 'Great Pyrenees', 1);
insert into breed (id, name, type_id) values (217, 'Greater Swiss Mountain Dog', 1);
insert into breed (id, name, type_id) values (218, 'Greyhound', 1);
insert into breed (id, name, type_id) values (219, 'Harrier', 1);
insert into breed (id, name, type_id) values (220, 'Havanese', 1);
insert into breed (id, name, type_id) values (221, 'Hound', 1);
insert into breed (id, name, type_id) values (222, 'Hovawart', 1);
insert into breed (id, name, type_id) values (223, 'Husky', 1);
insert into breed (id, name, type_id) values (224, 'Ibizan Hound', 1);
insert into breed (id, name, type_id) values (225, 'Icelandic Sheepdog', 1);
insert into breed (id, name, type_id) values (226, 'Illyrian Sheepdog', 1);
insert into breed (id, name, type_id) values (227, 'Irish Setter', 1);
insert into breed (id, name, type_id) values (228, 'Irish Terrier', 1);
insert into breed (id, name, type_id) values (229, 'Irish Water Spaniel', 1);
insert into breed (id, name, type_id) values (230, 'Irish Wolfhound', 1);
insert into breed (id, name, type_id) values (231, 'Italian Greyhound', 1);
insert into breed (id, name, type_id) values (232, 'Italian Spinone', 1);
insert into breed (id, name, type_id) values (233, 'Jack Russell Terrier', 1);
insert into breed (id, name, type_id) values (234, 'Jack Russell Terrier (Parson Russell Terrier)', 1);
insert into breed (id, name, type_id) values (235, 'Japanese Chin', 1);
insert into breed (id, name, type_id) values (236, 'Jindo', 1);
insert into breed (id, name, type_id) values (237, 'Kai Dog', 1);
insert into breed (id, name, type_id) values (238, 'Karelian Bear Dog', 1);
insert into breed (id, name, type_id) values (239, 'Keeshond', 1);
insert into breed (id, name, type_id) values (240, 'Kerry Blue Terrier', 1);
insert into breed (id, name, type_id) values (241, 'Kishu', 1);
insert into breed (id, name, type_id) values (242, 'Klee Kai', 1);
insert into breed (id, name, type_id) values (243, 'Komondor', 1);
insert into breed (id, name, type_id) values (244, 'Kuvasz', 1);
insert into breed (id, name, type_id) values (245, 'Kyi Leo', 1);
insert into breed (id, name, type_id) values (246, 'Labrador Retriever', 1);
insert into breed (id, name, type_id) values (247, 'Lakeland Terrier', 1);
insert into breed (id, name, type_id) values (248, 'Lancashire Heeler', 1);
insert into breed (id, name, type_id) values (249, 'Leonberger', 1);
insert into breed (id, name, type_id) values (250, 'Lhasa Apso', 1);
insert into breed (id, name, type_id) values (251, 'Lowchen', 1);
insert into breed (id, name, type_id) values (252, 'Maltese', 1);
insert into breed (id, name, type_id) values (253, 'Manchester Terrier', 1);
insert into breed (id, name, type_id) values (254, 'Maremma Sheepdog', 1);
insert into breed (id, name, type_id) values (255, 'Mastiff', 1);
insert into breed (id, name, type_id) values (256, 'McNab', 1);
insert into breed (id, name, type_id) values (257, 'Miniature Pinscher', 1);
insert into breed (id, name, type_id) values (258, 'Mountain Cur', 1);
insert into breed (id, name, type_id) values (259, 'Mountain Dog', 1);
insert into breed (id, name, type_id) values (260, 'Munsterlander', 1);
insert into breed (id, name, type_id) values (261, 'Neapolitan Mastiff', 1);
insert into breed (id, name, type_id) values (262, 'New Guinea Singing Dog', 1);
insert into breed (id, name, type_id) values (263, 'Newfoundland Dog', 1);
insert into breed (id, name, type_id) values (264, 'Norfolk Terrier', 1);
insert into breed (id, name, type_id) values (265, 'Norwegian Buhund', 1);
insert into breed (id, name, type_id) values (266, 'Norwegian Elkhound', 1);
insert into breed (id, name, type_id) values (267, 'Norwegian Lundehund', 1);
insert into breed (id, name, type_id) values (268, 'Norwich Terrier', 1);
insert into breed (id, name, type_id) values (269, 'Nova Scotia Duck-Tolling Retriever', 1);
insert into breed (id, name, type_id) values (270, 'Old English Sheepdog', 1);
insert into breed (id, name, type_id) values (271, 'Otterhound', 1);
insert into breed (id, name, type_id) values (272, 'Papillon', 1);
insert into breed (id, name, type_id) values (273, 'Patterdale Terrier (Fell Terrier)', 1);
insert into breed (id, name, type_id) values (274, 'Pekingese', 1);
insert into breed (id, name, type_id) values (275, 'Peruvian Inca Orchid', 1);
insert into breed (id, name, type_id) values (276, 'Petit Basset Griffon Vendeen', 1);
insert into breed (id, name, type_id) values (277, 'Pharaoh Hound', 1);
insert into breed (id, name, type_id) values (278, 'Pit Bull Terrier', 1);
insert into breed (id, name, type_id) values (279, 'Plott Hound', 1);
insert into breed (id, name, type_id) values (280, 'Podengo Portugueso', 1);
insert into breed (id, name, type_id) values (281, 'Pointer', 1);
insert into breed (id, name, type_id) values (282, 'Polish Lowland Sheepdog', 1);
insert into breed (id, name, type_id) values (283, 'Pomeranian', 1);
insert into breed (id, name, type_id) values (284, 'Poodle', 1);
insert into breed (id, name, type_id) values (285, 'Portuguese Water Dog', 1);
insert into breed (id, name, type_id) values (286, 'Presa Canario', 1);
insert into breed (id, name, type_id) values (287, 'Pug', 1);
insert into breed (id, name, type_id) values (288, 'Puli', 1);
insert into breed (id, name, type_id) values (289, 'Pumi', 1);
insert into breed (id, name, type_id) values (290, 'Rat Terrier', 1);
insert into breed (id, name, type_id) values (291, 'Redbone Coonhound', 1);
insert into breed (id, name, type_id) values (292, 'Retriever', 1);
insert into breed (id, name, type_id) values (293, 'Rhodesian Ridgeback', 1);
insert into breed (id, name, type_id) values (294, 'Rottweiler', 1);
insert into breed (id, name, type_id) values (295, 'Saint Bernard St. Bernard', 1);
insert into breed (id, name, type_id) values (296, 'Saluki', 1);
insert into breed (id, name, type_id) values (297, 'Samoyed', 1);
insert into breed (id, name, type_id) values (298, 'Sarplaninac', 1);
insert into breed (id, name, type_id) values (299, 'Schipperke', 1);
insert into breed (id, name, type_id) values (300, 'Schnauzer', 1);
insert into breed (id, name, type_id) values (301, 'Scottish Deerhound', 1);
insert into breed (id, name, type_id) values (302, 'Scottish Terrier Scottie', 1);
insert into breed (id, name, type_id) values (303, 'Sealyham Terrier', 1);
insert into breed (id, name, type_id) values (304, 'Setter', 1);
insert into breed (id, name, type_id) values (305, 'Shar Pei', 1);
insert into breed (id, name, type_id) values (306, 'Sheep Dog', 1);
insert into breed (id, name, type_id) values (307, 'Shepherd', 1);
insert into breed (id, name, type_id) values (308, 'Shetland Sheepdog Sheltie', 1);
insert into breed (id, name, type_id) values (309, 'Shiba Inu', 1);
insert into breed (id, name, type_id) values (310, 'Shih Tzu', 1);
insert into breed (id, name, type_id) values (311, 'Siberian Husky', 1);
insert into breed (id, name, type_id) values (312, 'Silky Terrier', 1);
insert into breed (id, name, type_id) values (313, 'Skye Terrier', 1);
insert into breed (id, name, type_id) values (314, 'Sloughi', 1);
insert into breed (id, name, type_id) values (315, 'Smooth Fox Terrier', 1);
insert into breed (id, name, type_id) values (316, 'South Russian Ovtcharka', 1);
insert into breed (id, name, type_id) values (317, 'Spaniel', 1);
insert into breed (id, name, type_id) values (318, 'Spitz', 1);
insert into breed (id, name, type_id) values (319, 'Staffordshire Bull Terrier', 1);
insert into breed (id, name, type_id) values (320, 'Standard Poodle', 1);
insert into breed (id, name, type_id) values (321, 'Sussex Spaniel', 1);
insert into breed (id, name, type_id) values (322, 'Swedish Vallhund', 1);
insert into breed (id, name, type_id) values (323, 'Terrier', 1);
insert into breed (id, name, type_id) values (324, 'Thai Ridgeback', 1);
insert into breed (id, name, type_id) values (325, 'Tibetan Mastiff', 1);
insert into breed (id, name, type_id) values (326, 'Tibetan Spaniel', 1);
insert into breed (id, name, type_id) values (327, 'Tibetan Terrier', 1);
insert into breed (id, name, type_id) values (328, 'Tosa Inu', 1);
insert into breed (id, name, type_id) values (329, 'Toy Fox Terrier', 1);
insert into breed (id, name, type_id) values (330, 'Treeing Walker Coonhound', 1);
insert into breed (id, name, type_id) values (331, 'Vizsla', 1);
insert into breed (id, name, type_id) values (332, 'Weimaraner', 1);
insert into breed (id, name, type_id) values (333, 'Welsh Corgi', 1);
insert into breed (id, name, type_id) values (334, 'Welsh Springer Spaniel', 1);
insert into breed (id, name, type_id) values (335, 'Welsh Terrier', 1);
insert into breed (id, name, type_id) values (336, 'West Highland White Terrier Westie', 1);
insert into breed (id, name, type_id) values (337, 'Wheaten Terrier', 1);
insert into breed (id, name, type_id) values (338, 'Whippet', 1);
insert into breed (id, name, type_id) values (339, 'White German Shepherd', 1);
insert into breed (id, name, type_id) values (340, 'Wire Fox Terrier', 1);
insert into breed (id, name, type_id) values (341, 'Wire-Haired Pointing Griffon', 1);
insert into breed (id, name, type_id) values (342, 'Wirehaired Terrier', 1);
insert into breed (id, name, type_id) values (343, 'Xoloitzcuintle (Mexican Hairless)', 1);
insert into breed (id, name, type_id) values (344, 'Yellow Labrador Retriever', 1);
insert into breed (id, name, type_id) values (345, 'Yorkshire Terrier Yorkie', 1);